# Generated by Django 6.0.5 on 2026-05-07 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place_type', models.CharField(choices=[('standard', 'Standard'), ('handicapped', 'Handicapped'), ('vip', 'VIP'), ('electric', 'Electric Vehicle')], default='standard', max_length=20)),
                ('base_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=6)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=6)),
                ('daily_max', models.DecimalField(decimal_places=2, default=20.0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='parkingplace',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='parkingplace',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingplace',
            name='place_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('handicapped', 'Handicapped'), ('vip', 'VIP'), ('electric', 'Electric Vehicle')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='is_subscription_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('truck', 'Truck'), ('electric', 'Electric Vehicle')], default='car', max_length=20),
        ),
        migrations.CreateModel(
            name='ParkingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('place_available', 'Place Available'), ('almost_full', 'Parking Almost Full'), ('full', 'Parking Full'), ('subscription_expiry', 'Subscription Expiring'), ('overstay', 'Vehicle Overstay')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='parking.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='parking.subscription'),
        ),
    ]
