# Generated by Django 6.0.5 on 2026-05-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parkingplace',
            unique_together={('company', 'number', 'floor')},
        ),
    ]
